name: Upload Config Files and Purge Akamai Cache

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    #paths:
    #  - common-configs/**
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch

jobs:
  upload-and-purge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Akamai CLI and NetStorage Module
        run: |
          set -e
          curl -sL https://github.com/akamai/cli/releases/download/v2.0.0/akamai-v2.0.0-linuxamd64 -o akamai
          chmod +x akamai
          sudo mv akamai /usr/local/bin/
          akamai install netstorage
          akamai install purge
          
          echo "[ccu]
          client_secret = ${{ secrets.AKAMAI_API_CLIENT_SECRET }}
          host = ${{ secrets.AKAMAI_API_CLIENT_HOST }}
          access_token = ${{ secrets.AKAMAI_API_CLIENT_ACCESS_TOKEN }}
          client_token = ${{ secrets.AKAMAI_API_CLIENT_CLIENT_TOKEN }}" > ~/.edgerc

          echo "[default]
          key = ${{ secrets.AKAMAI_NS_UPLOAD_ACCOUNT_KEY }}
          id = 1fe
          group = 1FE
          host = 1fe-nsu.akamaihd.net
          cpcode = 1800003" > ~/auth

      - name: Install rsync
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y rsync
          rsync --version || { echo "rsync installation failed"; exit 1; }

      - name: Sync directories to NetStorage using rsync
        run: |
          set -e

          # Write the SSH key from secrets to a file
          echo "${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}" > $HOME/key.pem
          chmod 600 $HOME/key.pem

          # Sync each folder's contents to NetStorage using rsync over SSH
          for folder in integration development production; do
            echo "Syncing contents of $folder to NetStorage..."
            rsync -avv --delete -RO --dry-run -e "ssh -o StrictHostKeyChecking=no -i $HOME/key.pem" "$folder/" "sshacs@1fe.rsync.upload.akamai.com:$folder"
          done

      - name: Upload config files to NetStorage
        run: |
          cp common-configs/integration.json live.json && akamai netstorage upload live.json --directory integration/configs --config ~/auth && rm live.json
          cp common-configs/stage.json live.json && akamai netstorage upload live.json --directory stage/configs --config ~/auth && rm live.json
          cp common-configs/demo.json live.json && akamai netstorage upload live.json --directory demo/configs --config ~/auth && rm live.json
          cp common-configs/production.json live.json && akamai netstorage upload live.json --directory production/configs --config ~/auth && rm live.json

      - name: Purge all assets with cache tag
        run: |
          set -e
          echo "Purging all assets with cache tag using akamai-purge..."
          akamai-purge --edgerc .edgerc cachePurgeByType --tag 1fe