name: Upload Config Files and Purge Akamai Cache

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch
    #paths:
    #  - common-configs/**

jobs:
  upload-and-purge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Akamai CLI and NetStorage Module
        run: |
          set -e
          curl -sL https://github.com/akamai/cli/releases/download/v2.0.0/akamai-v2.0.0-linuxamd64 -o akamai
          chmod +x akamai
          sudo mv akamai /usr/local/bin/
          akamai install netstorage
          akamai install purge
          
          set -e
          echo "[ccu]
          client_secret = ${{ secrets.AKAMAI_API_CLIENT_SECRET }}
          host = ${{ secrets.AKAMAI_API_CLIENT_HOST }}
          access_token = ${{ secrets.AKAMAI_API_CLIENT_ACCESS_TOKEN }}
          client_token = ${{ secrets.AKAMAI_API_CLIENT_CLIENT_TOKEN }}" > ~/.edgerc

          set -e
          echo "[default]
          key = ${{ secrets.AKAMAI_NS_UPLOAD_ACCOUNT_KEY }}
          id = 1fe
          group = 1FE
          host = 1fe-nsu.akamaihd.net
          cpcode = 1800003" > ~/auth

      - name: Upload config files to NetStorage
        run: |
          cp common-configs/integration.json live.json && akamai netstorage upload live.json --directory integration/configs --config ~/auth && rm live.json
          cp common-configs/stage.json live.json && akamai netstorage upload live.json --directory stage/configs --config ~/auth && rm live.json
          cp common-configs/demo.json live.json && akamai netstorage upload live.json --directory demo/configs --config ~/auth && rm live.json
          cp common-configs/production.json live.json && akamai netstorage upload live.json --directory production/configs --config ~/auth && rm live.json

      - name: Upload integration, development, and production folders to NetStorage
        run: |
          for folder in integration development production; do
            find "$folder" -type f | while read file; do
              echo "Uploading $file..."
              akamai netstorage upload "$file" --directory "$(dirname $file)" --config ~/auth
            done
          done
          
      - name: Purge assets to reset cache
        run: |
          set -e
          akamai purge invalidate https://1fe-a.akamaihd.net/integration/configs/live.json https://1fe-a.akamaihd.net/stage/configs/live.json https://1fe-a.akamaihd.net/demo/configs/live.json https://1fe-a.akamaihd.net/production/configs/live.json
          for folder in integration development production; do
            akamai purge invalidate "https://1fe-a.akamaihd.net/$folder/*"
          done