name: Upload Config Files and Purge Akamai Cache

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch
    #paths:
    #  - common-configs/**

# test

jobs:
  upload-and-purge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Akamai CLI and NetStorage Module
        run: |
          set -e
          curl -sL https://github.com/akamai/cli/releases/download/v2.0.0/akamai-v2.0.0-linuxamd64 -o akamai
          chmod +x akamai
          sudo mv akamai /usr/local/bin/
          akamai install netstorage
          akamai install purge
          
          set -e
          echo "[ccu]
          client_secret = ${{ secrets.AKAMAI_API_CLIENT_SECRET }}
          host = ${{ secrets.AKAMAI_API_CLIENT_HOST }}
          access_token = ${{ secrets.AKAMAI_API_CLIENT_ACCESS_TOKEN }}
          client_token = ${{ secrets.AKAMAI_API_CLIENT_CLIENT_TOKEN }}" > ~/.edgerc

          set -e
          echo "[default]
          key = ${{ secrets.AKAMAI_NS_UPLOAD_ACCOUNT_KEY }}
          id = 1fe
          group = 1FE
          host = 1fe-nsu.akamaihd.net
          cpcode = 1800003" > ~/auth

      - name: Install rsync
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y rsync
          rsync --version || { echo "rsync installation failed"; exit 1; }

      - name: Validate Akamai configuration files
        run: |
          set -e
          if [ ! -f ~/.edgerc ]; then
            echo "Error: ~/.edgerc file is missing."
            exit 1
          if [ ! -f ~/auth ]; then
            echo "Error: ~/auth file is missing."
            exit 1
          fi
          echo "Akamai configuration files are valid."

      - name: Upload config files to NetStorage
        run: |
          cp common-configs/integration.json live.json && akamai netstorage upload live.json --directory integration/configs --config ~/auth && rm live.json
          cp common-configs/stage.json live.json && akamai netstorage upload live.json --directory stage/configs --config ~/auth && rm live.json
          cp common-configs/demo.json live.json && akamai netstorage upload live.json --directory demo/configs --config ~/auth && rm live.json
          cp common-configs/production.json live.json && akamai netstorage upload live.json --directory production/configs --config ~/auth && rm live.json1``

      - name: Install rsync
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Sync directories to NetStorage using rsync
        run: |
          set -e
          for folder in integration development production; do
            echo "Syncing $folder to NetStorage..."
            rsync -av --delete "$folder/" "user@1fe-nsu.akamaihd.net::$folder" --password-file=~/auth || echo "Failed to sync $folder"
          done

      - name: Purge all assets with cache tag
        run: |
          set -e
          echo "Purging all assets with cache tag '1fe'..."
          akamai purge invalidate --tag 1fe || echo "Failed to purge assets with cache tag '1fe'"

      - name: Generate list of files to purge
        run: |
          for folder in integration development production; do
            find "$folder" -type f >> files_to_purge.txt
          done
          echo "Files to purge:"
          cat files_to_purge.txt

      - name: Purge individual files from Akamai cache
        run: |
          set -e
          while read file; do
            url="https://1fe-a.akamaihd.net/$file"
            echo "Purging $url..."
            akamai purge invalidate "$url" || echo "Failed to purge $url"
          done < files_to_purge.txt