name: Upload to CDN

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Akamai CLI and NetStorage Module
        run: |
          curl -sL https://github.com/akamai/cli/releases/download/v2.0.0/akamai-v2.0.0-linuxamd64 -o akamai
          chmod +x akamai
          sudo mv akamai /usr/local/bin/
          akamai install netstorage
          akamai install purge

      - name: Upload file to Akamai NetStorage
        run: |
          echo "[default]
          host = ${{ secrets.CDN_1FE_AKAMAI_HOST }}
          key = ${{ secrets.CDN_1FE_AKAMAI_SECRET }}
          cpcode = ${{ secrets.CDN_1FE_AKAMAI_CP_CODE }}" > ~/.akamai-cli/.netstorage

          akamai netstorage upload /common-configs/integration.json /integration/configs/live.json
          akamai netstorage upload /common-configs/stage.json /stage/configs/live.json
          akamai netstorage upload /common-configs/demo.json /demo/configs/live.json
          akamai netstorage upload /common-configs/production.json /production/configs/live.json

      - name: Purge assets to reset cache
        run: |
          akamai purge invalidate --hostname ${{ secrets.CDN_1FE_AKAMAI_HOST }} --objects "/integration/configs/live.json" "/stage/configs/live.json" "/demo/configs/live.json" "/production/configs/live.json"
